import Navbar from "@/components/Manual/Navbar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Web N Grapics",
  description: "Generated by Mostaque",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} bg-Mbg ${geistMono.variable} antialiased`}
      >
        <header>
          <Navbar />
        </header>
        <div>{children}</div>
      </body>
    </html>
  );
}
